services:
  db:
    image: postgres:16
    container_name: reco-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - reco_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"   # utile si ton Spring Boot tourne hors Docker

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  reco-job:
    build:
      context: ./reco-ml
    volumes:
      - ./reco-ml:/jobs
      - ./datasets:/datasets:ro
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  reco_data:
